FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir --progress-bar off setuptools wheel
RUN pip install --no-cache-dir --progress-bar off numpy==1.26.4 pandas==2.2.2 scipy==1.13.1
RUN pip install --no-cache-dir --progress-bar off scikit-learn==1.5.0 xgboost==2.0.3
COPY requirements.txt .
RUN pip install --no-cache-dir --progress-bar off -r requirements.txt
COPY . .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
